version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      legacy_translator:
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      legacy_translator:
  kafka-connect:
    container_name: kafka-connect
    image: tobiaszimmer/exam-prebuilt-images:kafka-connect-19-01-2022-12-03
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    networks:
      legacy_translator:

volumes:
  zookeeper_data:
  kafka_data:

networks:
  legacy_translator:
    external: true