version: "3.9"

services:
  postgres:
    container_name: postgres
    image: tobiaszimmer/exam-legacy-system:main-postgres
    ports:
      - "6969:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty!234
      POSTGRES_DB: food_delivery
    networks:
      legacy_translator:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      legacy_translator:
  food_to_go:
    depends_on:
      - postgres
      - redis
    container_name: food_to_go
    image: tobiaszimmer/exam-legacy-system:main-1.0.0
    ports:
      - "9085:9085"
      - "9080:9080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATA_SERVICE_URL: http://food_to_go:9080/
      DATA_SERVICE_JDBC_URL: jdbc:postgresql://postgres:5432/food_delivery
      DATA_SERVICE_POSTGRES_USERNAME: postgres
      DATA_SERVICE_POSTGRES_PASSWORD: Qwerty!234
    networks:
      legacy_translator:

networks:
  legacy_translator:
    external: true
