version: "3.9"

services:
  auth-postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    networks:
      legacy_translator:
  auth-service:
    depends_on:
      - auth-postgres
    image: tobiaszimmer/exam_auth_service:main-0.1.0
    environment:
      POSTGRES_HOST: auth-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: auth
      TOKEN_DURATION_HOURS: 12
      HAS_GATEWAY: false
    networks:
      legacy_translator:

networks:
  legacy_translator:
    external: true
