version: "3.9"

services:
  camunda-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      legacy_translator:
  camunda:
    image: tobiaszimmer/exam-camunda-server:processUpdate-0.0.3
    environment:
      DB_CONNECTION_STR: jdbc:postgresql://camunda-postgres:5432/postgres
      DB_USERNAME: postgres
      DB_POSTGRES: postgres
      CAMUNDA_ADMIN_USERNAME: demo
      CAMUNDA_ADMIN_PASSWORD: demo
      CAMUNDA_ADMIN_EMAIL: test@test.dk
      CAMUNDA_ADMIN_FIRSTNAME: admin
      CAMUNDA_ADMIN_LASTNAME: admin
    networks:
      legacy_translator:

networks:
  legacy_translator:
    external: true
