version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      legacy_translator:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      legacy_translator:
  kafka-connect:
    depends_on:
      - kafka
    image: tobiaszimmer/exam-prebuilt-images:kafka-connect-16-02-2022-12-04
    command:
      - sh
      - /start.sh
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
    networks:
      legacy_translator:

volumes:
  zookeeper_data:
  kafka_data:

networks:
  legacy_translator:
    external: true