name: Setup environment
description: "Action used to setup the environment"

runs:
  using: composite
  steps:
    - name: Setup environment
      shell: bash
      run: |
        docker network create legacy_translator
        docker compose -f kafka.docker-compose.yaml up -d
        sleep 5

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "temurin"
        cache: maven
